---
# tasks file for ansible-apt-upgrade

- block:
    - name: apt-get upgrade
      apt:
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        update_cache: yes
        upgrade: "{{ apt_upgrade_type }}"
  become: yes
  tags:
    - apt-upgrade
    - package-management
